version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build 1
          command: docker build -f Dockerfile_1 -t image_1:$CIRCLE_SHA1 .
      - run:
          name: build 2
          command: docker build -f Dockerfile_2 -t image_2:$CIRCLE_SHA1 .
